/* Implementation of double precision floating-point number generators
	 through division of a random integer by a constant integer.

	Copyright 2019--2020 University of Nantes, France.

	This file is part of the FPNGlib library.

	The FPNGlib library is free software; you can redistribute it and/or modify
	it under the terms of the GNU Lesser General Public License as published by the 
	Free Software Foundation; either version 3 of the License, or (at your
	option) any later version.
	
	The FPNGlib library is distributed in the hope that it will be useful, but
	WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
	or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
	for more details.
	
	You should have received copies of the GNU General Public License and the
	GNU Lesser General Public License along with the FPNGlib Library.  If not,
	see https://www.gnu.org/licenses/. 	
	
 */

/*
	Contrary to frng64_division.[ch], which uses all the bits of the random integer
	computed, this version uses only the $k$ lowest bits.
 */

#ifndef __fpngl_frng64_division_k_h__
#define __fpngl_frng64_division_k_h__

#include <fpnglib/fpngl_config.h>
#include <fpnglib/frng64_t.h>
#include <fpnglib/irng_t.h>

#ifdef __cplusplus
extern "C" {
#endif

	/*
		Generation of a random float by division of the result of an integer RNG `f`
		by a constant `c`.
		The FRNG created owns the IRNG passed as second parameter and is responsible
		for its destruction.

		The integer generated by `irng` is restricted to `k` bits before being divided by
		`denominator`.
	*/
	fpngl_frng64_t *fpngl_bydivision_k_new(const char *name,
																				 double min, double max,
																				 fpngl_irng_t *irng,
																				 uint32_t k,
																				 uint64_t denominator);
	/*
		Draw a double precision number  at random in the domain 
		``\{0\}\cup[2^{-53} ,1-2^{-53}]``.
	 */
	fpngl_frng64_t *fpngl_div53(fpngl_irng_t *irng, uint64_t seed);

	/*
		Draw a double precision number  at random in the domain 
		``\{0\}\cup[2^{-32} ,1-2^{-32}]``.
	 */
	fpngl_frng64_t *fpngl_div32(fpngl_irng_t *irng, uint64_t seed);

#ifdef __cplusplus
}
#endif

#endif // __fpngl_frng64_division_k_h__
